name: ChatApp Backend Main

on:
  workflow_dispatch:
  push:
    branches:
      - staging

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm i
      - name: Run Test
        run: echo "running test"

  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: echo "${{ secrets.PTA }}" |   docker login ghcr.io -u krishbale --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/krishbale/chat-apps-encryption-webhooks:chatapp .
      - name: Push Docker image to Docker Hub
        run: ghcr.io/krishbale/chat-apps-encryption-webhooks:chatapp


  # deployment:
  #   needs: dockerhub 
  #   runs-on: 
  #     - self-hosted
  #     - chat-app

  #   steps:
  #     - n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ame: Login to Docker Hub
  #       working-directory: /home/ubuntu/Documents/balkrishnatest/Chat-Apps-Encryption-Webhooks
  #       run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
  #     # - name: Pull Docker image using Docker Compose
  #       # working-directory: /home/ubuntu/Documents/balkrishnatest/Chat-Apps-Encryption-Webhooks
  #       # run: docker compose pull 
  #     - name: Run Docker containers using Docker Compose
  #       working-directory: /home/ubuntu/Documents/balkrishnatest/Chat-Apps-Encryption-Webhooks
  #       run: docker compose up -d
  #     - name : Clean Up Space
  #       run: docker system prune -af  
