name: ChatApp Backend Main
on:
    workflow_dispatch:
    push:
        branches:
            - staging
jobs:
    test:
        runs-on:
            - ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Install Dependencies
              run: npm i
            - name: Run Test
              run: echo "running test"

    dockerhub:
        runs-on:
          - ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Login to Docker Hub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            - name: Build Docker image
              run: docker build -t krishbale/chatapp:v1 .
            - name: Push Docker image to Docker Hub
              run: docker push krishbale/chatapp:v1
    

    deployment:
        needs: dockerhub 
        runs-on:
            - self-hosted
            - hrms-staging
        steps:
            - name: Pull Image and Run Containers
              working-directory: /home/ubuntu/Documents/virtuosway/hrms/hr_web_backend
              run: |
               echo ${{ secrets.TOKEN }} | docker login --username rpanta00 --password-stdin ghcr.io
               docker compose pull backend && docker compose up  -d backend --build --force-recreate
            - name: Clean Up Space
              run: docker system prune -af
        
        